In [ ]:
# The purpose of this notebook is to provide more examples on how to use simple APIs. 
# One of the applications we will use in this notebook is Random User Generator. 
# RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes.
# The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more

In [2]:
!pip install randomuser pandas

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas in c:\users\hoang\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hoang\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hoang\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hoang\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hoang\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hoang\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py): started
  Building wheel for randomuser (setup.py): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5090 sha256=12679cb9db2b2ebfbf3f2533e3b9cd43a2307e3aa4f6eb8f8a5da93d778b9809
  Stored in directory: c:\users\hoang\appdata\local\pip\cache\wheels\be\62\c8\71e1b48f4758ea5b78af7595d87178f628cde315a3326610ee
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

In [38]:
from randomuser import RandomUser
import pandas as pd

# Create a random user object r
r = RandomUser()

# get a list of 10 random user by using generate_user() function
some_list = r.generate_users(10)

# get full name by using get_ful_name() function
name = r.get_full_name()

# print 10 user

for user in some_list:
    print(user.get_full_name() + user.get_email())

# generate photos of the random 10 users.
for user in some_list:
    print(user.get_picture())

# write function to create 10 user with full name, gender, city, state, email, DOB, picture

def get_users(a):
    data = []
    for user in RandomUser.generate_users(a):
        data.append({"Name":user.get_full_name(), "Gender": user.get_gender(), "City": user.get_city(), "State": user.get_state(), "Email": user.get_email(), "DOB": user.get_dob(),"Picture": user.get_picture()})
         
    return pd.DataFrame(data)
get_users(10)

Justin Gilljustin.gill@example.com
Samu Peralasamu.perala@example.com
Kelya Sanchezkelya.sanchez@example.com
Lyam Guerinlyam.guerin@example.com
Ece Okumuşece.okumus@example.com
Cory Reidcory.reid@example.com
Inger Van Asseldonkinger.vanasseldonk@example.com
Theo Carpentertheo.carpenter@example.com
Adolfo Martinezadolfo.martinez@example.com
Susanna Rogersusanna.roger@example.com
https://randomuser.me/api/portraits/men/45.jpg
https://randomuser.me/api/portraits/men/2.jpg
https://randomuser.me/api/portraits/women/27.jpg
https://randomuser.me/api/portraits/men/20.jpg
https://randomuser.me/api/portraits/women/5.jpg
https://randomuser.me/api/portraits/men/70.jpg
https://randomuser.me/api/portraits/women/80.jpg
https://randomuser.me/api/portraits/men/50.jpg
https://randomuser.me/api/portraits/men/67.jpg
https://randomuser.me/api/portraits/women/86.jpg

,Name,Gender,City,State,Email,DOB,Picture
0,Ilham Roelink,female,Halsteren,Limburg,ilham.roelink@example.com,1963-11-15T10:41:16.586Z,https://randomuser.me/api/portraits/women/71.jpg
1,Nurdan Demirel,female,Trabzon,Iğdır,nurdan.demirel@example.com,1953-01-07T05:46:12.415Z,https://randomuser.me/api/portraits/women/0.jpg
2,Rosa Rojas,female,Orihuela,Castilla y León,rosa.rojas@example.com,1946-02-09T06:35:11.875Z,https://randomuser.me/api/portraits/women/39.jpg
3,Tomothy Green,male,Tamworth,Tasmania,tomothy.green@example.com,1997-05-21T21:44:04.365Z,https://randomuser.me/api/portraits/men/76.jpg
4,Herman Riley,male,Adelaide,Northern Territory,herman.riley@example.com,1965-12-03T04:24:15.408Z,https://randomuser.me/api/portraits/men/92.jpg
5,Brooklyn Ward,female,Minneapolis,North Dakota,brooklyn.ward@example.com,1962-08-06T05:42:36.723Z,https://randomuser.me/api/portraits/women/81.jpg
6,Arnaud Chan,male,Brockton,Yukon,arnaud.chan@example.com,1963-11-28T19:08:52.772Z,https://randomuser.me/api/portraits/men/18.jpg
7,Deniz Sözeri,female,Burdur,Iğdır,deniz.sozeri@example.com,1969-04-06T18:18:43.369Z,https://randomuser.me/api/portraits/women/79.jpg
8,Damaris Dumont,female,Laufen-Uhwiesen,St. Gallen,damaris.dumont@example.com,1959-02-27T07:53:16.872Z,https://randomuser.me/api/portraits/women/17.jpg
9,Florian Guillot,male,Montreuil,Finistère,florian.guillot@example.com,1956-02-21T17:58:48.278Z,https://randomuser.me/api/portraits/men/78.jpg

In [ ]:
# more common way to use APIs, is through requests library. Requests and HTTP, will contain more information about requests.

In [7]:
import requests
import json
import pandas as pd

# obtain the fruityvice API data using requests.get("url") function. The data is in a json format.
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")

# retrieve result using json.load() function
results = json.loads(data.text)

#convert results to data frame

pd.DataFrame(results)

#The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.
df = pd.json_normalize(results)
pd.set_option("display.width",100) # increase max width
pd.set_option("display.max_columns",None) # show all column

#show data fram info
print(df.info())

# show first 5 row
print(df.head())

# find out how many calories are contained in a banana.

banana = df.loc[df["name"] == "Banana"].reset_index(drop = True)
print(f"A banana contains {banana.loc[0,"nutritions.protein"]} protein")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      49 non-null     object
 1   id                        49 non-null     int64
 2   family                    49 non-null     object
 3   order                     49 non-null     object
 4   genus                     49 non-null     object
 5   nutritions.calories       49 non-null     int64
 6   nutritions.fat            49 non-null     float64
 7   nutritions.sugar          49 non-null     float64
 8   nutritions.carbohydrates  49 non-null     float64
 9   nutritions.protein        49 non-null     float64
dtypes: float64(4), int64(2), object(4)
memory usage: 4.0+ KB
None
         name  id      family         order      genus  nutritions.calories  nutritions.fat  \
0   Persimmon  52   Ebenaceae       Rosales  Diospyros                   81             0.0
1  Strawberry   3    Rosaceae       Rosales   Fragaria                   29             0.4
2      Banana   1    Musaceae  Zingiberales       Musa                   96             0.2
3      Tomato   5  Solanaceae     Solanales    Solanum                   74             0.2
4        Pear   4    Rosaceae       Rosales      Pyrus                   57             0.1

   nutritions.sugar  nutritions.carbohydrates  nutritions.protein
0              18.0                      18.0                 0.0
1               5.4                       5.5                 0.8
2              17.2                      22.0                 1.0
3               2.6                       3.9                 0.9
4              10.0                      15.0                 0.4
A banana contains 1.0 protein

In [ ]:
#This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.

# https://official-joke-api.appspot.com/jokes/ten

In [19]:
import pandas as pd
import requests
import json

url = "https://official-joke-api.appspot.com/jokes/ten"

# retrieve data  
data = requests.get(url)

# retrieve result using json.loads() function
results = json.loads(data.text)

# convert to data frame
pd.DataFrame(results)

# flatten data
df = pd.json_normalize(results)

print(df.head()) # show first 5 row

#Drop the type and id columns.
df.drop(columns = ["type","id"],inplace=True)
df

          type                                              setup  \
0      general                    Why did the math book look sad?
1      general  I saw a nice stereo on Craigslist for $1. Sell...
2  programming      Why did the programmer always carry a pencil?
3  programming         Why dot net developers don't wear glasses?
4      general               Why did the cookie go to the doctor?

                           punchline   id
0  Because it had too many problems.  422
1           I couldn’t turn it down.  370
2     They preferred to write in C#.  448
3            Because they see sharp.  376
4    Because it was feeling crumbly.  434

                                               setup                                    punchline
0                    Why did the math book look sad?            Because it had too many problems.
1  I saw a nice stereo on Craigslist for $1. Sell...                     I couldn’t turn it down.
2      Why did the programmer always carry a pencil?               They preferred to write in C#.
3         Why dot net developers don't wear glasses?                      Because they see sharp.
4               Why did the cookie go to the doctor?              Because it was feeling crumbly.
5         What did one plate say to the other plate?                             Dinner is on me!
6           What kind of music do planets listen to?                                   Nep-tunes.
7                 Why was the developer always calm?  Because they knew how to handle exceptions.
8          Where do you learn to make banana splits?                            At sundae school.
9  Have you ever heard of a music group called Ce...                            They mostly wrap.